image: alpine/edge
packages:
  - texlive
  - texmf-dist-latexextra
  - texmf-dist-science
  - py3-pygments
sources:
  - https://git.sr.ht/~anaveragehuman/notes
tasks:
  - build: |
      cd notes
      latexmk -pdf -gg -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape
